#
# spec file for package samplellama
#
# Copyright (c) 2025 SUSE LLC
#
# All modifications and additions to the file contributed by third parties
# remain the property of their copyright owners, unless otherwise agreed
# upon. The license for this file, and modifications and additions to the
# file, is the same license as for the pristine package itself (unless the
# license for the pristine package is not an Open Source License, in which
# case the license is the MIT License). An "Open Source License" is a
# license that conforms to the Open Source Definition (Version 1.9)
# published by the Open Source Initiative.

# Please submit bugfixes or comments via https://bugs.opensuse.org/
#

Name:           samplellama
Version:        0.1.0
Release:        1.vojtech
Summary:        Ollama-to-MCP sampling bridge
License:        MIT
URL:            https://github.com/vojtechpavlik/samplellama

# Source0 (Application) and Source1 (Vendor) are generated by the _service file
Source0:        %{name}-%{version}.tar.gz
Source1:        vendor.tar.gz

BuildRequires:  go >= 1.23
BuildRequires:  systemd-rpm-macros

%{?systemd_requires}

%description
Samplellama is a bridge that lets tools built for the Ollama API use any
LLM accessible through an MCP (Model Context Protocol) host. It runs as
an MCP server and simultaneously exposes an Ollama-compatible HTTP API.

%prep
%autosetup -p1 -a 1

%build
CGO_ENABLED=0 go build \
   -mod=vendor \
   -buildmode=pie \
   -ldflags="-w -s" \
   -o samplellama

%install
install -D -m 0755 samplellama %{buildroot}%{_bindir}/samplellama
install -D -m 0644 samplellama.service %{buildroot}%{_unitdir}/%{name}.service
install -D -m 0644 samplellama.1 %{buildroot}%{_mandir}/man1/samplellama.1

%check
go test ./...

%pre
%service_add_pre %{name}.service

%post
%service_add_post %{name}.service

%preun
%service_del_preun %{name}.service

%postun
%service_del_postun %{name}.service

%files
%license LICENSE
%doc README.md DESIGN.md
%{_bindir}/samplellama
%{_unitdir}/%{name}.service
%{_mandir}/man1/samplellama.1*

%changelog
